wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650927126
    t:
      1:
      - 11
      - 12
      - 45
      - 49
      - 55
      2:
      - 11
      - 12
      - 45
      - 49
      - 55
      4: 3.9.7
      5: 0.12.15
      6: 4.18.0
      8:
      - 5
